// app/layout.tsx (NÃO USE "use client" aqui!)
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";
import ClientLayout from "./ClientLayout"; // novo wrapper

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
